variables:
  FAVER: "5.6.3"

stages:
  - tikz
  - book

tikz:
  image: registry.gitlab.com/claut/man_ccia/tinytex
  stage: tikz
  script:
    - cd tikz
    - for D in 0 1 2 3 4; do pdflatex -shell-escape "${D}d.tex"; done
    - mkdir -p ../img
    - cp *.png ../img/
  artifacts:
    expire_in: 1h
    paths:
      - img

test:
  image: registry.gitlab.com/claut/man_ccia/book
  stage: book
  script:
    - make fontawesome
    - make book
  artifacts:
    expire_in: 1w
    paths:
    - public
  except:
  - main

pages:
  image: registry.gitlab.com/claut/man_ccia/book
  stage: book
  script:
    - make fontawesome
    - make book
  artifacts:
    expire_in: 1h
    paths:
    - public
  only:
  - main
