# Introduction {#intro}

_Last update: `r system("git log -1 --format=\"%ad (%h)\" -- 01-intro.Rmd", intern = TRUE)`_

```{r setup, include=FALSE}
source("R/init_python.R")
source("R/deco_hook.R")
```

Climate change is a critical issue facing our generation, and has been called the "greatest challenge of our time" by Dr. Thomas F. Stocker, the former co-chairman of the IPCC Working Group I [@gillis2013climate]. At the University of Toronto Scarborough, EES1117 "Climate Change Impact Assessment" (CCIA) focuses on projecting the regional impacts of the changing global climate, and is, arguably, the academic centrepiece of the M.Env.Sc. Climate Change Impacts and Adaptation stream. This lab manual is a companion to that course, and is designed to walk you through a detailed CCIA process.

## Learning outcomes

Throughout the course of this book, you will learn how to acquire observed historical climate data from Environment and Climate Change Canada, and perform basic analyses of a climatic exposure unit and meteorological variables (Lab `r which(grepl("eccc", list.files(pattern = ".*_lab.Rmd")))`; Sec. \@ref(eccclab)). We will show you have to navigate multi-dimesional these data sets, and extract the information that is relevant to your analysis (Lab `r which(grepl("dims", list.files(pattern = ".*_lab.Rmd")))`, Sec. \@ref(dimslab)). In Lab `r which(grepl("select", list.files(pattern = ".*_lab.Rmd")))` (Sec. \@ref(selectlab)), you will use these data to project changes in your exposure unit through the year 2100. In Lab `r which(grepl("pcic", list.files(pattern = ".*_lab.Rmd")))` (Sec. \@ref(pciclab)), we will show you how to acquire statistically downscaled climate data for Canada (Sec. \@ref(pcic)), and we will use that data to improve our CCIA projections. Finally, in Lab `r which(grepl("esgf", list.files(pattern = ".*_lab.Rmd")))` (Sec. \@ref(esgflab)), you will learn how to acquire raw GCM data from the Earth System Grid Federation (ESGF), the source for data from the Coupled Model Intercomparison Project Phase 5 (CMIP5), this will allowwou to expand your analyses to different models and variables.

Along the way, you will learn some general information about climate model hierarchy and scenarios Sec. \@ref(modelling)), and some model selection strategies (and whether you should use any of them) (Sec. \@ref(modelselection)). In addition to these field-specific skills, you will learn all about the netCDF file format, and multidimensional data series (Sec. \@ref(dimensions)). You will also learn a lot of code! The examples in this book are written in Python, but you are welcome to use any programming language in which you are comfortable. All of the exercises herein should be relatively easy to port to R or another statistical language of your choosing. 

## Syntax used in this manual

To help you navigate this book, we will use a specific syntax.

- **bold** is used for the names of Python libraries or modules.
- _italic_ is used when referencing things like filenames, URLs, email addresses and file extensions. 
- `constant width` is used to indicate code, commands, or output, as well as variable names and the names of executable files.

You will also sometimes find specially-formatted call out boxes. These boxes are meant to provide you with helpful tips, important warnings, or provide exercises for you to check your understanding. The boxes look like this:

```{block, type='rmdassignment'}
This is work that you should complete to check your understanding of the material presented in each lab.
```

```{block, type='rmdtip'}
This is a tip.
```

```{block, type='rmdcomment'}
This is a comment.
```

```{block, type='rmddisclaimer'}
This is a warning or other disclaimer.
```

The code blocks in this book have been labelled with the icon and name of the programming language. Most of the blocks are Python code, but you will see a few commands that need to be entered in a command prompt or terminal outside of Python. 

```{python, deco=list()}
print("This is Python code!")
```

```{bash, deco=list(label="Shell", bc="#000000", tc="#ffffff", icon=list(style="fas", name="terminal"))}
echo "This is code in your shell (e.g. Bash)!"
```


## Ready. Set. Go.

We hope that you find this manual engaging as well as informative. As we already mentioned in the preface of this book, we happily welcome your contributions and comments by reporting [issues](https://gitlab.com/claut/man_ccia/issues) with the book (anything as small as a typo or as large as an erroneous explanation) or submitting [merge requests](https://gitlab.com/claut/man_ccia/merge_requests) to the project to add content or make corrections. Let's get started. Section \@ref(enviro) will walk you through installing the necessary programs and packages that you will need to complete this lab manual. 
