# Acknowledgements and Appreciation {#thanks}

A huge "thank you" goes out to the first cohort of students to use this lab manual: the winter 2019 EES1117 class. These folks put up with a ton of typos, some code errors, less-than-clear exercise questions, and frequent tweaks and experimentation. Thanks (in alphabetical order) to:

 - Andrew Apostoli
 - Maralgua Batdelger
 - [Dean Boulding](https://gitlab.com/claut/man_ccia/-/issues?scope=all&state=all&author_username=jakartadean) (extra points for opening an issue on GitLab)
 - Samuel Brockmeyer
 - Mathieu Brunette
 - Kenneth Chow
 - Erik Dean
 - Hongda Ding
 - Minwen (Amy) Guo
 - Lee (Allie) Ho
 - Alexander Lau
 - Haotian Luo
 - Ricky Wong
 - Minghan (Chase) Yang

Thank you, also, to Paul Kushner for sharing your experience using the book and identifying typos and bugs. 

Thanks to [Alfonso Reyes](https://gitlab.com/claut/man_ccia/-/merge_requests?scope=all&state=opened&author_username=AlfonsoRReyes) for suggestions to make it easier to build the book locally. 

Thank you to [Julia Wagemann](https://gitlab.com/claut/man_ccia/-/issues?scope=all&state=all&author_username=julia.wagemann) and [Jeremy Fyke](https://gitlab.com/claut/man_ccia/-/issues?scope=all&state=all&author_username=JeremyFyke) for their fantastic comments and thorough [review](https://github.com/openjournals/jose-reviews/issues/100) of this manual as part of our submission to [JOSE](https://jose.theoj.org/about).
